version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - user-service
      - donation-service
      - notification-service

  user-service:
    build: ./services/user-service
    ports:
      - "5001:5001"
    environment:
      - MYSQL_HOST=mysql
    depends_on:
      - mysql

  donation-service:
    build: ./services/donation-service
    ports:
      - "5002:5002"
    depends_on:
      - mongo

  notification-service:
    build: ./services/notification-service
    ports:
      - "5003:5003"
    depends_on:
      - redis

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: userdb
    ports:
      - "3306:3306"

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"
